import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# --- INSTAGRAM CONFIG ---
IG_USER = "samsepi.0l"
IG_PASS = "a5bVq2tjL3pCKIYoQFAhAXzCYJp$*x1l&eF9P*%B"
SESSION_FILE = "session.json"

# --- OPENAI CONFIG ---
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY") or "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"

# --- ROCKETAPI CONFIG ---
ROCKET_API_KEY = os.getenv("ROCKET_API_KEY") or "YOUR_ROCKET_API_KEY"
ROCKET_API_BASE_URL = "https://v1.rocketapi.io/instagram"

# --- KEYWORDS ---
from .names import MALE_KEYWORDS, FEMALE_KEYWORDS
IGNORE_WORDS = {"follow", "following", "message", "contact", "suggested", "connect", "remove", "live", "reels", "posts", "followers", "search", "verified"}

# --- KNOWN INFLUENCERS / SAFE ACCOUNTS (Knowledge Base) ---
KNOWN_INFLUENCERS = {
    # --- GLOBAL ICONS (Music, Sport, Celeb) ---
    "cristiano", "leomessi", "selenagomez", "kyliejenner", "therock", 
    "arianagrande", "kimkardashian", "beyonce", "khloekardashian", "justinbieber",
    "kendalljenner", "taylorswift", "virat.kohli", "jlo", "nickiminaj", 
    "kourtneykardash", "mileycyrus", "neymarjr", "katyperry", "zendaya", 
    "kevinhart4real", "iamcardib", "kingjames", "ddlovato", "badgalriri", 
    "chrisbrownofficial", "champagnepapi", "ellendegeneres", "k.mbappe", 
    "billieeilish", "gal_gadot", "lalalalisa_m", "vindiesel", "shakira", 
    "priyankachopra", "snoopdogg", "jennierubyjane", "davidbeckham", "dualipa", 
    "khaby00", "mrbeast", "karimbenzema", "ronaldinho", "paulpogba", 
    "sergioramos", "mosalah", "paulywala", "akshaykumar", "deepikapadukone",
    "emmawatson", "garethbale11", "zlayanibrahimovic", "jamescharles", 
    "hudabeauty", "nusr_et", "cznburak", "danlabilic", "khabib_nurmagomedov",
    "conormcgregor", "floydmayweather", "loganpaul", "jakepaul", "pewdiepie",
    "addisonraee", "charlidamelio", "dixiedamelio", "zachking", "bellapoarch",
    "willsmith", "leonardodicaprio", "robertdowneyjr", "chrishemsworth", "vancityreynolds",
    "blakelively", "gigihadid", "bellahadid", "haileybieber", "shawnmendes",
    "camila_cabello", "harrystyles", "niallhoran", "liampayne", "zayn",
    "louist91", "adele", "edsheeran", "brunomars", "theweeknd",
    "postmalone", "travisscott", "kanyewest", "drake", "eminem",
    "rihanna", "ladygaga", "madonna", "britneyspears", "xtina",
    "jenniferaniston", "courteneycoxofficial", "lisakudrow", "mleblanc", "matthewperry",
    "david.schwimmer", "tomholland2013", "zendaya", "chrispratt", "chrisevans",
    "markruffalo", "jeremyrenner", "scarlettjohanssonworld", "elizabetholsenofficial", "prattprattpratt",

    # --- TURKEY (TR) TOP INFLUENCERS ---
    "handemiyy", "burakozcivit", "muratboz", "demetakalin", "elcinsangu", 
    "eda.ece", "karikaturhane", "ekremimamoglu", "tuvanaturkay", "yasemoz88", 
    "oguzhanugur_", "aslienver", "nasuhistanbuli", "neslimgungen", 
    "ozgecangurelofficial", "gulben123", "cmylmz", "enginaltandzytn", 
    "dilandeniz", "pelinkarahan", "gamze_ercel", "caglasikel", "mcanunverdi", 
    "iremhlvcioglu", "halukleventacil", "selincigerci", "mrtyldrm", "burcues", 
    "sahangokbakar", "nurgulyesilcayy", "pelinsu_", "yavasmansur", 
    "yasmine__belkacem", "nezdemir", "burcubiricik", "akinakinozu", 
    "muratovucofficiall", "eylulonline", "ecesuuckan", "yagmurtanrisevsin", 
    "sedasayan", "roportajadam", "hadise", "acunilicali", "reynmen", "berkcan",
    "ece.seckin", "mervebolugur", "serenayss", "hazalkaya", "fahriyevcen", 
    "neslihanatagul", "berguzarkorels", "halitergencresmi", "kivancatatlitug", 
    "cagatayulusoy", "arasbulutiynemli", "tolgasaritas", "barisarduc", 
    "kerembursin", "demetozdemir", "can_yaman", "alpnavruz", "aycaaysinturan", 
    "afra.saracoglu", "mert_ramazan_demir", "ertassla", "didiniav", "alenayavas",
    "alisasezensever", "atavratmiyav", "zeynepesensoy", "misrapower", "ilaydasurucuu",
    "ilaydamertl", "eso1es", "uberkuloz", "furkankorkmaz", "senayildirim",
    "cemretorun", "selincinar", "ilhanersahin", "meldayazicioglu", "muratbakis",
    "yektaunalan", "selva", "ecem", "talyasever", "cenkkaracalar",
    "zuhal", "ismailkopmaz", "hamiozkan", "rterdogan", "ardaturan",
    "evcenf", "umutisler", "tahaozer", "cznburak", "nusr_et",

    # --- AZERBAIJAN (AZ) TOP INFLUENCERS ---
    "royaofficial", "batu.karam", "sevinc_sevil", "chagaev4x20", "shafaqnovruz", 
    "rozazergerli", "diana_ahadpour", "trend.hediyye", "kamilzeynalli", 
    "vusalaalizade", "fatimafataliofficial", "sameddin_photographer", 
    "toylar_mekani", "em_kids_studio", "ilkin_photographer", "afsarmirzoyev", 
    "belllaatate", "fuadsahverdiyev", "nicatguliev", "sadixli", "nicoagazade", 
    "ramzimirzayev", "orkhanaslanov", "__hissiz", "orxideya_bridalroom", 
    "floral_arts_baku", "aina_wedding_room", "rashad_nabiyev", 
    "fatime_vusalqizi_official", "_boutiqueone_", "eminqurbanovwed", 
    "samiraslanov", "microblading_tunzale", "sadiqalyv", "elshanja_", 
    "parfum.baki", "edu_camp_azerbaijan", "salmanov_photographer", "xina.az", 
    "elnurashuroff", "sabirmammadov", "gfarique", "oguz_ritm", "party_time_art", 
    "tarlanazizovphoto", "kg_weddinghouse", "ttfightclub", "araz.bagirov", 
    "bella_pizza_baku", "luckgifts", "sevfrise", "moreofmegg", 
    "after_effects_tutorialss", "alamdarmanafov", "vusaleshixcan", "gurbankhans", 
    "lalekh", "bossynm", "mahivybz", "xa1ida", "natavan_habibi", "gunay_ibrahimli",
    "zaur_gunay", "aygun_kazimova", "brilliant_dadashova", "miri_yusif",
    "leyla999", "aynikhalid", "anar_agakishiev", "aysel.shukur", "subo_m",
    "chingizallazov", "by_aitanfarzaliyeva", "leila_land", "sabiorudjeva", "moouradi",
    "wefegm", "bahram_bagirzade", "shabnam_tovuzlu", "nadjiba_ahmedi", "vusala_aliyeva",
    "mehin_oktayli", "shabnam_farajzada", "aygun_babayeva", "alixan_recebov", "ulviyya_namazova",
    "elmira_namazova", "ulya_khalinbekova", "arzu_mammadova", "sabir_samiroglu", "hamayil_alasgarova",
    "nigar_guliyeva", "nigar_rufat", "retro_azerbaijan", "aygul_guliyeva", "yasemen_aliyeva",
    "gunel_farhadli", "nazrin", "ayten_novruzova", "nushaba_gandil", "nigar_kalbiyeva",
    "ayla_bakhtiyarova", "maral_zeinalova", "eldar_gasimov", "javid_bayramli", "victoria",
    "hanum_aziz", "abd_malik", "lamiya_valiyeva", "yelena_eyvazli", "seym", "igoguseinov",

    # --- RUSSIA/CIS & REGIONAL ---
    "timatiofficial", "buzova86", "borodylia", "ververa", "urgantcom", 
    "nagiev.universal", "pavelvolyaofficial", "garikkharlamov", "m_galustyan", 
    "samburskaya", "offi_hanna", "egorkreed", "nyusha_nyusha", "klavacoca", 
    "morgen_shtern", "instasamka", "dina", "rahimabram", "kuzmin_vitaliy", 
    "surnov83", "dimachyornyy", "kamenev99", "irinashayk", "gusein.gasanov",
    "mariasharapova", "ler_chek", "agentgirl", "goar_avetisyan", "samoylovaoxana",
    "mikhail_litvin", "dava_m", "vasilisa.volodina", "zolotov.producer", "bytregubov",
    "nadin_ellize", "piletskayaa.ya", "i_am_doshik", "khatuna.akhobadz", "sevarainlove",
    "slavalenka", "esipchenish", "misssvikki", "miss_taisia", "namsilat",
    "katyaa_golden", "kseniasukhinova", "by_julia_ismailova", "olya.des", "maxgalkinru",
    "alla_orfey", "kirkorov", "bilanofficial", "lazarevsergey", "polina_gagarina",
    "lobodaofficial", "anilorak", "valeriya", "prigozhin_iosif", "shnurovs",

    # --- BRANDS & ORGS (Fashion, Tech, Food, Sports) ---
    "nike", "adidas", "zara", "hm", "gucci", "louisvuitton", "chanel", "dior", 
    "prada", "versace", "fendi", "balenciaga", "puma", "reebok", "underarmour", 
    "victoriassecret", "calvinklein", "tommyhilfiger", "burberry", "hermes", 
    "rolex", "tiffanyandco", "cartier", "apple", "samsung", "google", 
    "microsoft", "amazon", "netflix", "disney", "marvel", "starwars", "nba", 
    "nfl", "mlb", "fifaworldcup", "championsleague", "premierleague", "laliga", 
    "bundesliga", "seriea", "ufc", "wwe", "f1", "mercedesamgf1", "scuderiaferrari", 
    "redbullracing", "mclaren", "natgeo", "nasa", "spacex", "tesla", 
    "lamborghini", "ferrari", "porsche", "bmw", "mercedesbenz", "audi", 
    "bugatti", "rollsroyce", "bentley", "astonmartin", "maserati", "jaguar", 
    "landrover", "jeep", "toyota", "honda", "nissan", "ford", "chevrolet", 
    "dodge", "starbucks", "mcdonalds", "burgerking", "kfc", "subway", 
    "dominos", "pizzahut", "cocacola", "pepsi", "redbull", "monsterenergy",
    "kyliecosmetics", "sweetgreen", "auntieannes", "cheetos", "garnier", "tsa",
    "teva", "gopro", "bershka", "pullandbear", "stradivarius", "massimodutti",
    "oyysho", "volkswagen", "hyundai", "kia", "mazda", "lexus", "subaru",
    "volvo", "mini", "fiat", "alfaromeo", "citroen", "peugeot", "renault",
    "skoda", "seat", "dacia", "suzuki", "mitsubishi", "isuzu", "yamahamotor",
    "kawasaki", "ducati", "harleydavidson", "triumph", "royalenfield", "ktm",
    "husqvarna", "aprilia", "vespa", "piaggio", "kymco", "sym",
    "sony", "playstation", "xbox", "nintendo", "twitch", "youtube",
    "tiktok", "snapchat", "pinterest", "linkedin", "twitter", "facebook",
    "whatsapp", "telegram", "viber", "skype", "zoom", "slack",
    "discord", "reddit", "tumblr", "flickr", "vimeo", "dailymotion",
    "spotify", "applemusic", "tidal", "deezer", "soundcloud", "shazam",
    "uber", "lyft", "airbnb", "bookingcom", "expedia", "tripadvisor",
    "trivago", "kayak", "skyscanner", "agoda", "hotelscom", "vrbo",
    "zomato", "ubereats", "doordash", "grubhub", "deliveroo", "justeat",
    "glovo", "wolt", "talabat", "foodpanda", "instacart", "gopuff",
    "asos", "boohoo", "prettylittlething", "missguided", "fashionnova", "shein",
    "romwe", "zaful", "forever21", "urbanoutfitters", "anthropologie", "freepeople",
    "nordstrom", "bloomingdales", "macys", "saks", "neimanmarcus", "bergdorfs",
    "sephora", "ulta", "mac", "nars", "urbandecay", "toofaced",
    "benefitcosmetics", "anastasiabeverlyhills", "morphe", "colourpop", "glossier", "fentybeauty",
    "huda", "kkwbeauty", "hauslabs", "rarebeauty", "rembeauty", "florencebymills",
    "rhode", "skims", "savagexfenty", "yeezy", "off____white", "supreme",
    "palace", "stussy", "bape", "kith", "fearofgod", "essentials",
    "vetements", "acnestudios", "jacquemus", "bottegaveneta", "saintlaurent", "valentino",
    "givenchy", "alexandermcqueen", "dolcegabbana", "armani", "moschino", "kenzo",
    "moncler", "canadagoose", "thenorthface", "patagonia", "columbia", "arcteryx",
    "salomon", "hoka", "on_running", "newbalance", "asics", "vans",
    "converse", "dr_martens", "timberland", "ugg", "crocs", "birkenstock",
    "rayban", "oakley", "persol", "warbyparker", "gentlemonster", "sunglasshut",
    "swarovski", "pandora", "mejuri", "missoma", "gorjana", "baublebar",
    "lego", "barbie", "hotwheels", "fisherprice", "mattel", "hasbro",
    "funko", "pokemon", "sanrio", "hellokitty", "gudetama", "pusheen",
    "bts.bighitofficial", "blackpinkofficial", "twice", "straykids", "exo", "nct",
    "seventeen", "txt_bighit", "enhypen", "itzy", "aespa", "ive",
    "newjeans_official", "lesserafim", "gidle", "mamamoo", "redvelvet", "shinee",
    "superjunior", "bigbang", "2ne1", "girlsgeneration", "wondergirls", "missa",
    "sistar", "kara", "tara", "4minute", "fx", "browneyedgirls",
    "realmadrid", "fcbarcelona", "manchesterunited", "liverpoolfc", "chelseafc", "arsenal",
    "mancity", "spursofficial", "juventus", "acmilan", "inter", "asroma",
    "napoli", "psg", "fcbayern", "bvb09", "atleticodemadrid", "sevillafc",
    "valenciacf", "ajax", "psv", "feyenoord", "benfica", "fcporto",
    "sportingcp", "galatasaray", "fenerbahce", "besiktas", "trabzonspor", "basaksehir",
    "celtics", "lakers", "warriors", "bulls", "knicks", "nets",
    "heat", "bucks", "sixers", "suns", "mavericks", "nuggets",
    "clippers", "rockets", "spurs", "jazz", "blazers", "kings",
    "thunder", "timberwolves", "pelicans", "grizzlies", "magic", "hornets",
    "hawks", "pacers", "pistons", "cavaliers", "wizards", "raptors",
    "yankees", "redsox", "dodgers", "cubs", "giants", "mets",
    "cardinals", "braves", "phillies", "nationals", "astros", "rangers",
    "cowboys", "patriots", "steelers", "packers", "49ers", "chiefs",
    "raiders", "eagles", "giants", "bears", "broncos", "seahawks",
    "saints", "vikings", "dolphins", "bills", "jets", "ravens",
    "browns", "bengals", "titans", "colts", "jaguars", "texans",
    "buccaneers", "panthers", "falcons", "lions", "ramsnfl", "chargers",
    "cardinals", "commanders", "nhl", "mapleleafs", "canadiens", "bruins",
    "rangers", "blackhawks", "redwings", "penguins", "capitals", "flyers",
    "kings", "sharks", "ducks", "goldenknights", "kraken", "canucks",
    "flames", "oilers", "jets", "senators", "lightning", "panthers",
    "hurricanes", "predators", "stars", "wild", "blues", "avalanche",
    "coyotes", "sabres", "devils", "islanders", "bluejackets", "cbssports",
    "espn", "foxsports", "nbcsports", "skysports", "btsport", "dazn",
    "eurosport", "beinsports", "bleacherreport", "houseofhighlights", "sportscenter", "barstoolsports"
}
