import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export default function TermsOfService() {
    return (
        <div className="min-h-screen bg-[#050505] text-gray-300 font-sans flex flex-col">
            <Navbar />
            <main className="flex-grow max-w-4xl mx-auto px-6 py-32">
                <h1 className="text-4xl md:text-5xl font-mono font-bold text-white mb-8">Terms of Service</h1>

                <div className="space-y-6">
                    <p>Last Updated: November 26, 2025</p>

                    <div className="border border-neon-red/50 bg-neon-red/10 p-6 rounded-lg my-8">
                        <p className="text-neon-red font-bold font-mono text-lg text-center">
                            THIS SERVICE IS FOR ENTERTAINMENT PURPOSES ONLY. WE ARE NOT RESPONSIBLE FOR BROKEN RELATIONSHIPS OR EMOTIONAL DAMAGE.
                        </p>
                    </div>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-mono text-white">1. Acceptance of Terms</h2>
                        <p>
                            By accessing or using Caught in 4k, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use our services.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-mono text-white">2. Description of Service</h2>
                        <p>
                            Caught in 4k provides an AI-powered analysis tool for entertainment purposes. The results generated by our service are based on algorithmic patterns and should not be taken as definitive proof of fidelity or infidelity.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-mono text-white">3. User Conduct</h2>
                        <p>
                            You agree not to use the service for any illegal purpose or to harass, stalk, or harm others. You are solely responsible for the content you upload and the consequences of sharing the results.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-mono text-white">4. Disclaimer of Warranties</h2>
                        <p>
                            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
                        </p>
                    </section>
                </div>
            </main>
            <Footer />
        </div>
    );
}
